export const LOAD_OPTIONS = 'MEMORY_BOARD:LOAD_OPTIONS';
export const FLIP_OPTION = 'MEMORY_BOARD:FLIP_OPTION';
export const INCREMENT_SCORE = 'MEMORY_BOARD:INCREMENT_SCORE';
export const DECREMENT_SCORE = 'MEMORY_BOARD:DECREMENT_SCORE';
